### ISSUE TITLE
switch from `pylint` to `ruff`

### ISSUE THREAD

**Issue by hechth** [matchms/sparsestack#24]
We could also switch from `pylint` to `ruff` as we just also did for MS2DeepScore.

The workflow would need something like this:
```
      - name: Check style against standards using Ruff
        run: ruff check .
```

And we could add a config file `ruff.toml` or `.ruff.toml`, e.g. like this [ruff.toml](https://github.com/matchms/ms2deepscore/blob/main/ruff.toml). In principle this should also work with something like `tool.ruff` in the existing toml-file.

_Originally posted by @florian-huber in https://github.com/matchms/sparsestack/issues/22#issuecomment-2456438283_

**Comment by florian-huber** [comment]
Fixed with #28
